# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
   - 2.7

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

install:
    - conda create -q -n test_env python=$TRAVIS_PYTHON_VERSION six numpy
    - source activate test_env
    - conda install nose wxpython
    - python setup.py install

script:
    - nosetests
